### PR TITLE
Adding Bold Surface Forms: Issue #353

### PR DESCRIPTION
**Pull request by abhishekg2389**
File changes for extracting bold Mentions/Surface Forms of the Entity. #353

### CODE REVIEW

**Comment by tgalery** [comment]
Hi @abhishekg2389 could you provide a test case for the bold sf ?Also, we have to look where the code is used. It's likely that it is called by the pignlproc tool, which uses spotlight as a dependency to generate the surface form store. Maybe you could double check that as well ?

**Comment by abhishekg2389** [comment]
Hi @tgalery, Here are some test cases:
[1] http://en.wikipedia.org/wiki/Stanford_University
[2] http://en.wikipedia.org/wiki/Aon_%28company%29
[3] http://en.wikipedia.org/wiki/Phi_Gamma_Delta
[4] http://en.wikipedia.org/wiki/Radio_Warwick
[5] http://en.wikipedia.org/wiki/Afroasiatic_languages
[6] http://en.wikipedia.org/wiki/Analysis_of_variance
For e.g. in [2] "**Aon plc**" is given in bold which might be a Mention/Surface Form for "Aon (Company)".

Moreover I have inserted the code at a proper place if we are creating the surface form store as mentioned in the process in [Internationalization (Lucene backed Core)](https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Internationalization-(Lucene-backed-core))

**Comment by tgalery** [comment]
@abhishekg2389 , the lucene backend core is deprecated, so if this code is only used there, it won't probably have an effect on the whole surface form generation. The main repo that does that is this one https://github.com/dbpedia-spotlight/pignlproc , you can take a look at the pig scripts in the `examples/indexing` folder, but last time I checked I didn't see any scala code being called. I think there are some java util files that do the markup processing, so if you think you should re-implement your idea there, it might be a good way to go.
As for test cases, I meant unit tests, e.g. having some mocked up markup that you can test whether the bold face words where actually extracted.

**Comment by abhishekg2389** [comment]
Hi @tgalery,

I have raised a PR for this: https://github.com/dbpedia-spotlight/pignlproc/pull/17
Can you please check?

**Comment by dav009** [comment]
this seems to be a good example: http://en.wikipedia.org/wiki/Brian_Eno
It would be good to get some tests tho.

**Comment by tgalery** [comment]
I agree with @dav009, it would be good to have some tests for that.

**Comment by abhishekg2389** [comment]
Hi @dav009 and @tgalery,

I have updated the unit test and committed in dbpedia-spotlight/pignlproc#17

**Comment by dav009** [comment]
I will check it out by the weekend.
On a side note: This seems to be a good idea to improve on wiki2vec's entity coverage.

**Pull request closed without merging**
